LINKEDIN_TASKS = [
    {
        "id": "linkedin_1",
        "role": "Software Engineer",
        "experience_years": 2,
        "skills": ["Java", "Spring Boot", "REST APIs", "MySQL", "Docker"],
        "current_company": "a fintech startup",
        "goal": "Get noticed by product-based company recruiters",
        "weak_bio": "Software engineer. I like coding and solving problems. Looking for new opportunities.",
    },
    {
        "id": "linkedin_2",
        "role": "Frontend Developer",
        "experience_years": 1,
        "skills": ["React", "JavaScript", "TypeScript", "CSS", "Figma"],
        "current_company": "an e-commerce company",
        "goal": "Attract startup recruiters in Bangalore",
        "weak_bio": "Frontend dev. I build websites. Open to work.",
    },
    {
        "id": "linkedin_3",
        "role": "Data Engineer",
        "experience_years": 3,
        "skills": ["Python", "Apache Spark", "Airflow", "AWS", "PostgreSQL"],
        "current_company": "a SaaS company",
        "goal": "Move into a senior data engineering role",
        "weak_bio": "I work with data. Python and SQL. Looking for data jobs.",
    },
    {
        "id": "linkedin_4",
        "role": "DevOps Engineer",
        "experience_years": 2,
        "skills": ["Kubernetes", "Docker", "Terraform", "AWS", "CI/CD"],
        "current_company": "a cloud services company",
        "goal": "Land a role at a top product company",
        "weak_bio": "DevOps guy. I manage servers and deployments.",
    },
    {
        "id": "linkedin_5",
        "role": "Full Stack Engineer",
        "experience_years": 2,
        "skills": ["React", "Node.js", "MongoDB", "AWS", "GraphQL"],
        "current_company": "a B2B startup",
        "goal": "Get referrals from senior engineers at top companies",
        "weak_bio": "Full stack developer. I do both frontend and backend.",
    },
]